Re: #913 add filterDates method to QueryFactory
gdbots/ncr-php pull request #22
Opened 2019-09-11 18:19 UTC by cohencodes

#21

2019-09-11 19:40 UTC, efjacobson submitted a review, later dismissed
over to you @gdbrown

2019-09-12 01:55 UTC, gdbrown requested changes
@cohencodes this is out of sync with master.  should be v1.0.9 now.  v1.0.8 was tagged with the old strategy and this is replacing it

2019-09-13 01:36 UTC, gdbrown requested changes
@cohencodes we also need to call this method in the forSearchNodesRequest... https://github.com/gdbots/ncr-php/blob/c79e95b8ca06780dccc06729d5ac4501a4452cf5/src/Search/Elastica/QueryFactory.php#L54

2019-09-13 16:05 UTC, gdbrown approved these changes

2019-09-13 16:05 UTC, merged